FROM redis
MAINTAINER Raül Pérez <repejota@gmail.com>

#COPY redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

# Export service
EXPOSE 6379

CMD ["redis-server"]
